name: Release
on:
  push:
    tags: [ 'v*.*.*' ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}


jobs:
  build-image:
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ steps.meta.outputs.tags }}
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@96383f45573cb7f253c731d3b3ab81c87ef81934 # v5.0.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5.0.0
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  update-deployment:
    name: Update YAML Files for Deployment
    runs-on: ubuntu-latest
    needs: build-image

    steps:
    - name: Check out code
      uses: actions/checkout@v2
      with:
        ref: main

    - name: Update Image Tag Values
      run: |
        new_image_tag=${{ needs.build-image.outputs.image-tag }}
        sed -i.back "/image:/s/:v[0-9].*/:$new_image_tag/g" deploy/deployment.yaml
    
    - name: Commit the changes made
      run: | 
        git config --global user.name 'eagle8089'
        git config --global user.email 'nknikhilporuppath@gmail.com'
        git commit -am "updating image tag"
        git push
